# Generated by Django 3.1.6 on 2021-05-23 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0004_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='image',
            field=models.ImageField(default=None, upload_to='review'),
            preserve_default=False,
        ),
    ]
